### ISSUE TITLE
Add a comment section to each notebook

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#11]
Allow users to comment on notebooks (and the owner to manage comments).

**Comment by fenwanderer** [comment]
Consider [acts_as_commentable_with_threading](https://github.com/elight/acts_as_commentable_with_threading).

**Comment by jeffyjefflabs** [comment]
Done  using [commontator](https://github.com/lml/commontator).  Commontator does not do threading, but it provides its own views so is easy to integrate.
