### ISSUE TITLE
Add a user metrics page

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#13]
Add a page to show each user metrics for their owned notebooks--views, runs, stars, etc.  Model it after the notebook metrics page.

**Comment by manfromjupyter** [comment]
We've decided this would be too taxing on the system to compile on demand at this time and there are no decent extensions we can use for displaying it but perhaps with later versions of Rails or if we move to a different language entirely with other libraries that can used it may be possible. If it must be done or if users need a workaround, we recommend you write an extension just to push the data to an external application so it can be responsible for appropriately displaying, making accessible, etc.
