### ISSUE TITLE
JupyterHub support?

### ISSUE THREAD

**Issue by elgalu** [nbgallery/nbgallery#141]
https://github.com/jupyterhub/jupyterhub

**Comment by mcrutch** [comment]
You either need to have Jupyter Hub use one of our containers (preferably nbgallery/base-notebook) as the Jupyter Notebook container OR roll your own container that includes the nbgallery extensions (either extend from our base-notebook and add other things or add the nbgallery extensions to a different image) 

Then just pass along the appropriate environment variables so it knows the url for your gallery installation.   That should work, we have talked to at least one person using Hub with NBGallery, but I haven't personally set one up yet.

**Comment by alexanghh** [comment]
I have setup jupyterhub and is able to link to nbgallery. 

Simply install the nbgallery extension using the root user and new users should have the nbgallery installed by default (when the notebook config gets copied over for the initial setup). Users then have to set up their own link in nbgallery to allow the “run in jupyter” functionality (just submit a notebook and it will be auto added to the notebook link in nbgallery). 
Ps: remember to allow cross site.

**Comment by mcrutch** [comment]
I have a pull request in to the [nbgallery/docker-images](https://github.com/nbgallery/docker-images) repo which tells you how to use the nbgallery/base-notebook docker image that has the plugins as part of the hub so that it integrates with NBG much easier.
