### ISSUE TITLE
Pass gallery URL in metadata when executing "Run in Jupyter"

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#154]
When sending a Notebook to Jupyter, add one more metadata field to the notebook for the gallery url so that the extensions can be modified to use that field for reporting metrics/health/saving to gallery.  NBGallery Extensions for Jupyter will also be modified to support this field as an override for the extension.
Strip this value off when saved to the gallery.
Solves two problems:
Gallery URL changes
Supporting multiple gallery instances from one Notebook instance.

**Comment by mcrutch** [comment]
@jeffyjefflabs metadata, gallery, gallery_url?

**Comment by jeffyjefflabs** [comment]
Sounds good to me!
