### ISSUE TITLE
Add list view for search results

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#16]
Running a search displays the matching notebook tiles, but if there are many it would be helpful to have a list view (or possibly two with different levels of detail).  Allow the user to choose what view they prefer.  Make the list view sortable by field.

**Comment by manfromjupyter** [comment]
Old ticket, but enhancement for a list view for search with filters was added to the product ~3-4 months ago.

![search query - new](https://user-images.githubusercontent.com/51969207/70442190-d1132a00-1a63-11ea-8a8e-d4a39e20aecc.PNG)
