### ISSUE TITLE
JupyterHub NBgallery integration https

### ISSUE THREAD

**Issue by djb412** [nbgallery/nbgallery#169]
I was able to build and have everything run locally on localhost. I'm now getting errors after I get JupyterHub running on https: when trying to upload to nbgallery.  Mixed content the notebook was loaded over https but the http endpoint was insecure. How can I set up NBGallery over https? 
![NBGalleryError](https://user-images.githubusercontent.com/1396579/81423649-bd5b1500-9122-11ea-838e-07847ca5a3c6.png)

**Comment by jeffyjefflabs** [comment]
In production, we've used an nginx proxy in front of nbgallery to handle https -> http with rails itself still running plain http.  In development, I use a self-signed certificate (generated with `openssl` tool) with puma - see [this section](https://github.com/puma/puma#binding-tcp--sockets) of the puma docs for examples (or [this gist](https://gist.github.com/tadast/9932075) includes some of the openssl commands too).  If you google for "rails https" you'll find a few other options - I personally haven't tried anything else, and some of them require code changes, so nginx or puma are probably easiest depending on your situation.

**Comment by mcrutch** [comment]
Looks like Jeff gave a clear answer and there wasn't any follow-on so I am closing out this issue.
