### ISSUE TITLE
Add friends/followers capability

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#17]
Allow users to follow each other.  Ensure the user has reciprocal privacy settings to match.

This is kind of an extension of #12, as anything in the activity feed would be a candidate for sharing: notebook creation, publication, edits, etc.  Can add comments (see #11) as well.  Could also expose stars/likes, views, runs, joining a group, etc.

Would a follower just get to see an in-app activity feed for the user, or would they actually get a push notification of some sort?

Need to figure out how this would work with groups (e.g. when a user edits a notebook in a group that a follower doesn't belong to).

**Comment by fenwanderer** [comment]
Consider the [acts_as_follower](https://github.com/tcocca/acts_as_follower) gem.

**Comment by manfromjupyter** [comment]
Subscriptions has taken the parts of this features we wanted to add. Only thing it's missing is the owner of the notebook knowing who is their subscribers... which we could enable at any time but have elected for now not to. Closing as "Already fixed"
