### ISSUE TITLE
Ability to provide a user-friendly version # on upload of a new (and initial) revision (separate from the commit_id)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#181]
Instead of version "9f4a4a33", it can be whatever they want as long as it's alphanumeric, below 8 characters, but including periods. Version "3.0C", "1.1.2", "8", "D", etc. 

Not sure if this is even possible but will look cleaner when using older revisions, doing version compares, etc and will make it easier to talk about in a business environment (ex. "Version 1.0 to 3.6B work as well as 4.1 to 5.5. 3.6C was giving people problems, but we fixed that pretty quickly.")

**Comment by mcrutch** [comment]
It wouldn't be an instead of, it will be an also.  the version IDs that are there there are how they are tracked in git, so they have to remain.  The friendly display version would have to be tracked in addition to that.

**Comment by manfromjupyter** [comment]
Oh right. Makes sense. I like it.
