### ISSUE TITLE
Replace all bootstrap confirmation dialogs with a singular one we can customize accessibility wise

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#182]
Replace all bootstrap confirmation dialogs with a singular one we can customize accessibility wise

- Coloring of buttons is not consistent with our product
- Tabbing through the modal is not consistent with our product or fully accessible
- Missing modal header
- Verbiage can just be "Are you sure?" and will probably be a second quicker than the other dialog because it's loaded with the page DOM. This new dialog can apply to all places we already have one (ex. deleting notebook) and add one where we need them but don't at the moment (ex. deleting environment, deleting org chart, etc)

**Comment by manfromjupyter** [comment]
Confirmation dialog was created in a previous ticket and all deletion dialogs have been moved over, but not non-deletions if there are any. Keeping this open to flush out the rest that need to be convert over.

**Comment by mcrutch** [comment]
Is this just waiting the end of Death to Bootbox?  Or was this something else?

**Comment by manfromjupyter** [comment]
So kind of but no. There are a handful of confirmation or yes/no dialogs still that need to be converted over in my opinion still. I just know I couldn't get around to all of them yet which is why I kept this open to figure out what ones... Will start working on a list right now to confirm

**Comment by manfromjupyter** [comment]
Oh actually yes. This is part of death to bootbox. That one covers more but I see the following still I had intended to take care of:
1. Deleting staged notebooks (confirmation dialog)
2. Select Jupyter Environment
3. Overwrite notebook dialog (when saving from Jupyter to NBG)
4. When running in Jupyter fails 
5. Deleting external resources

**Comment by mcrutch** [comment]
Items 2, 3,  and 4 are working in #773

**Comment by mcrutch** [comment]
@manfromjupyter was going to tackle item 5
