### ISSUE TITLE
Markdown for descriptions not applied for notebook listings

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#185]
May be expected behavior for performance reasons but making ticket to open the discussion.

![markdown not working in listings](https://user-images.githubusercontent.com/51969207/85038710-ed9bc780-b154-11ea-9982-65d470cba2c6.PNG)

**Comment by mcrutch** [comment]
Pretty sure that will truncate the description if it is long, so parsing markdown that might terminate arbitrarily is probably not a good idea.

**Comment by mcrutch** [comment]
Working as intended.  We truncate the description at 500 characters so you might have two bad scenarios:
1 - Do markdown first then truncate which could leave open tags
2 - Truncate then do markdown which could lead to links going places that aren't intended
