### ISSUE TITLE
Metadata for Gallery URL in Notebook

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#187]
When sending notebooks to the Jupyter environment, in the notebook metadata (which currently includes the commit id, notebook uuid) and the gallery URL will be in this function.

Then when saving a notebook strip out the gallery URL (as it will now belong to the gallery it was uploaded to, and saves us from having to deal with URL changes in the future for the gallery).

**Comment by mcrutch** [comment]
Already merged in a different ticket #172

**Comment by jeffyjefflabs** [comment]
Stripping it back out during upload/save is new though, right?  Or did I miss that change?

**Comment by mcrutch** [comment]
Oh, yeah, missed that part. The code force writes it on the way out for run-in-juypter, do we maybe want to keep it there when uploaded in case we need the traceability or do we want to strip it if it is there?

**Comment by mcrutch** [comment]
As part of staging Gallery Metadata is already stripped, so we should be fine.
