### ISSUE TITLE
Minor Fix - on ultra dark theme, make subscribe icon same color as star icon on hover, etc

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#188]
Currently the start icon is gold and the subscribe icon is blue (should both be gold on ultra dark theme)

**Comment by mcrutch** [comment]
The blue on mouse-over for subscribe and star is also different from the blue on mouse-over for download, feedback, comments.... in the ultradark theme

**Comment by manfromjupyter** [comment]
That is intentional (at least on default theme) because the subscription and stars are yellow and the other buttons are orange. When inverted they are different blue colors. It might be better to keep these the same across all themes (always gold for the first two and always orange for the others on hover).
