### ISSUE TITLE
Find way to look at all notebooks that don't have a recognizable language (missing kernals for it)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#189]
Find way to look at all notebooks that don't have a recognizable language (missing kernals for it).

Ex. if someone added a new notebook with the Shakespeare Programming Language, we will be able to find which of those notebooks is the rebel if there are thousands of total notebooks.

**Comment by mcrutch** [comment]
I made up one and it displayed fine on the Languages page, so not sure what the purpose of this ticket is. There is also "unknown" if no kernel spec is supplied.

**Comment by mcrutch** [comment]
![image](https://user-images.githubusercontent.com/51446717/85142516-80e90180-b216-11ea-84b1-f231d018577f.png)

**Comment by manfromjupyter** [comment]
Hmmmm. Does it display the notebook listing when clicking on "Unknown" or "Shakespearian"? I don't exactly remember what the issue was, but we couldn't find what notebooks were these languages without looking at the database.

**Comment by manfromjupyter** [comment]
Closing because it seems to already be fixed. Will in another ticket just tweak the css of the unknown/default nb_gallery_language_icon to make it look prettier.. Nothing it wrong here though
