### ISSUE TITLE
Make Gallery Communication Error less alarming for private notebooks

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#19]
When a user:

* logs in to nbgallery,
* uploads a **private** notebook from their integrated Jupyter (e.g. jupyter-docker),
* logs out of nbgallery, and
* later re-opens the copy of the notebook in their integrated Jupyter,

they get a Gallery Communication Error from [gallery_notebook.js#L179](https://github.com/nbgallery/nbgallery/blob/15c6e82/public/integration/gallery_notebook.js#L179).  This is expected behavior (because Jupyter can't see the private notebook unless the user authenticates with nbgallery), but the error modal is verbose and may be alarming for new users.  This situation is likely to arise relatively frequently as users upload unfinished notebooks privately.

Suggest redesigning the modal to make this clearer and less alarming:

* Don't pop up the modal until it's really needed (e.g. when checking for changes).
* Don't present it as an error unless it's really necessary (e.g. the remote copy is really gone).
* Prompt/redirect the user to sign in to nbgallery if they aren't already.

Thoughts?

**Comment by jeffyjefflabs** [comment]
You could use the status code to adjust the dialog text... 404 => notebook was deleted or you typed it wrong when manually linking; 403 => was made private or you need to log in; timeout => gallery is down

**Comment by mcrutch** [comment]
Classic extensions aren't getting updates,, Lab we can look at tweaking this, but nothing will be done in NBGallery source.
