### ISSUE TITLE
Modals need to be announced when opened (Accessibility)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#191]
This is super important if not required for accessibility. We have it so the focus changes and the next read or tab is in the modal (and the action leading up to the modals lets them know an action would happen), but an announcement is required.

**Comment by mcrutch** [comment]
Is this still an outstanding issue?

**Comment by mcrutch** [comment]
@manfromjupyter - With the end of bootbox are we ok here?

**Comment by manfromjupyter** [comment]
@mcrutch I need to look into it again. I see no potential blockers at least

**Comment by manfromjupyter** [comment]
@mcrutch I will work on this right now. Yes it's still needed and viable. I'll look to inject a screen reader alert in JS whenever the base modal.show() is used and add aria-haspopup attributes to all of those buttons in the HTML. This way users know exactly what the button will do before they hit it AND screen readers will be informed they have appeared when they appear (the WCAG requirement)
