### ISSUE TITLE
Hide disabled notebooks from Jupyter starred and recently executed notebooks lists

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#196]
Back in March, 2020 a feature was added to deprecated and disable notebooks. Upon disabling the notebook is not capable of being run but users can still navigate to the direct URL in Jupyter to run it. If there is a way we can prevent this from NBGallery's source code, do it here so if the environment changes or varies with other user's project, it will always work. May not be plausible but worth checking out

EDIT: Find way to prevent disabled notebooks from showing up in Jupyter's Starred notebooks or Recently Executed notebooks

**Comment by mcrutch** [comment]
Can't prevent Juptyer from executing it (short of weird changes to the NBGallery plug), best we can do is make sure it is not auto-downloaded for the starred or recently executed notebooks

**Comment by manfromjupyter** [comment]
Oh yes, that makes more sense/rings a bell! Thank you

**Comment by mcrutch** [comment]
To do this cleanly, we should make "disabled" notebooks excluded from search by default, add a toggle to show disabled notebooks, then have the starred page default to not showing disabled
