### ISSUE TITLE
Docker Compose ?

### ISSUE THREAD

**Issue by britishbadger** [nbgallery/nbgallery#20]
Would it be possible to add a docker-compose file to simplify getting up and running? Will you accept pull requests ?

**Comment by somedave** [comment]
A docker-compose file has been on our to-do list but unfortunately we haven't had time to get to it yet. We'd love a pull request if you're interested in putting it together though.   Thanks!

**Comment by jeffyjefflabs** [comment]
We recently accepted PR #24, which added a compose file and associated config.  I'm going to close this, but please let us know if you see any problems with it or have other suggestions for getting nbgallery up and running.  Thanks!
