### ISSUE TITLE
On Admin banner page, gray out the submit button until the user fills out both fields AND selects either Info or Error

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#200]
On Admin banner page, gray out the submit button until the user fills out both fields AND selects either Info or Error

**Comment by mcrutch** [comment]
This appears to currently be the case

**Comment by mcrutch** [comment]
![image](https://user-images.githubusercontent.com/51446717/87795047-85083f00-c815-11ea-919b-32680d3f40f3.png)
They have a slight grey overlay and the denied mouse cursor.

**Comment by mcrutch** [comment]
@manfromjupyter When we talked about this ages ago, you said it was still a problem, but didn't elaborate on where you saw it, how to reproduce it.  Either provide additional information or this ticket is getting closed at the end of next week.

**Comment by manfromjupyter** [comment]
@mcrutch, This is fixed now, but as of June 30, the fields were fixed but the info/error button was not selected after returning back to it. Thank you.
