### ISSUE TITLE
Change HTML of alerts so that the Close is outside of the accessibility announcement.

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#202]
A little bit hard to explain but when an alert appears it interrupts the users due to changes that have been added for and if user is an accessibility user. Every time it announces it though it included the word "Close" at the end of it because we have the close icon in the same general container/block as the text that is being announced. Need to either move the close icon out or make the announcement `role="alert"` just around the text.

**Comment by mcrutch** [comment]
Closing per comment in merge request #644
