### ISSUE TITLE
Going back to home page from notebook page, causes tab issue

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#219]
User just noticed this.

1. Go to home page
2. Select tab other than the first one and note the results should look like.
3. Select one of those notebooks.
4. Press back on the browser and you will notice the selected tab is the one you were just on but the results are that of Recommended not the tab selected.

**Comment by mcrutch** [comment]
This is not the behavior I am seeing...when I go "back" it re-selects the recommended tab.

**Comment by manfromjupyter** [comment]
Shoot yeah, I'm not seeing it either. I'll close this for now. We'll talk later. I'm not crazy
