### ISSUE TITLE
Group permissions levels need documentation

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#230]
Document difference between Group Owner, Group Editor and Group Member in a way accessible to the user.

**Comment by mcrutch** [comment]
Thoughts @manfromjupyter @jeffyjefflabs? Also, sanity check the permissions
![image](https://user-images.githubusercontent.com/51446717/86783551-75774200-c02e-11ea-9ee4-4c7662b91abe.png)

**Comment by jeffyjefflabs** [comment]
Looks good to me!

**Comment by manfromjupyter** [comment]
Verbiage and placement seems good. Should we maybe wrap this in a info-alert container though (the light blue one)?
example in Slim:
```
  div.alert.alert-info.modal-alert
     i.fa.fa-info-circle aria-hidden="true"
     ul
       li Owner - ...
       li Editor - ...
       li Member - ...
```
