### ISSUE TITLE
Jupyterhub integration environment variables

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#271]
Hi, I'm looking at upgrading our nbgallery instance to include the jupyterhub integration. I was looking at the docker-compose for it, and was wondering what the env vars were for I don't see any documentation about them anywhere. 
https://github.com/nbgallery/nbgallery/blob/7787e49bc3c3b8e4b095ff1743872b318e60bd4f/docker-compose-with-jupyter.yml#L10-L13

**Comment by mcrutch** [comment]
NBGALLERY_ENABLE_INSTRUMENTATION and NBGALLERY_ENABLE_AUTODOWNLOAD are to turn on those two extensions in our jupyter image by default (nbgallery/base-notebook image from the nbgallery/docker-images/base-notebook repo)

The other two variables appear to be legacy from the old alpine container and do not work. 

See the [documentation here](https://github.com/nbgallery/docker-images/tree/master/base-notebook) about integrating with JupyterHub with our notebook image.

**Comment by cccs-cat001** [comment]
So to integrate I just need those to ENABLE ones and the URL eh?

**Comment by mcrutch** [comment]
And the different 'cmd' statement per the docs I linked.

**Comment by cccs-cat001** [comment]
Awesome thank you :)
