### ISSUE TITLE
Not able to save changes back to Gallery from Jupyter Notebook server

### ISSUE THREAD

**Issue by phungc** [nbgallery/nbgallery#29]
"Run In Jupyter" button works and sends the notebook to "jupyter-notebook-server:8888". However, nbgallery-extensions fails to "Save Changes to Gallery" with error below. 

Is there a way to set 'Access-Control-Allow-Origin' to the Origin 'http://jupyter-notebook-server:8888' instead of the wildcard '*'? 

Thanks,

Failed to load http://nbgallery-server:3000/notebooks/17ca76ad-fc82-4979-8a3b-8e47fade9a16/metadata?seconds=1531502550.167: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://jupyter-notebook-server:8888' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by somedave** [comment]
Let me know if this works for you @phungc - this was a change I forgot to push, sorry.

**Comment by phungc** [comment]
Thank you @somedave It works
