### ISSUE TITLE
Remove all absolute paths from .slim files

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#291]
There are instances of hardcoded directory paths (such as "/notebooks" on the search form).  These need to be relative OR use rails values to base them on the application root

**Comment by mcrutch** [comment]
url_for should be the path forward here, unless you find something better.

**Comment by jeffyjefflabs** [comment]
link_to is good too depending on what you're doing

**Comment by mcrutch** [comment]
Added fun will be all the Javascript files that use "/" as a fixed path as well....will need to make a javascript variable from a view that can be used everywhere.
