### ISSUE TITLE
Add Email column to All users page

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#298]
Would be useful to be able to show/filter by email address on admin all users page

**Comment by mcrutch** [comment]
@manfromjupyter 
Any thoughts on a clean way to hide/show columns so that we can have the email column maybe as an additional column that can be added but isn't always there?  Because this column can be really useful.
![image](https://user-images.githubusercontent.com/51446717/94801575-3c900480-03b4-11eb-92b2-eca188a4018f.png)

**Comment by mcrutch** [comment]
code is in branch https://github.com/nbgallery/nbgallery/tree/email-on-userlist

**Comment by manfromjupyter** [comment]
@mcrutch sorry I am so incredibly late on this. What did you decide with that branch as I don't see it. Still want this?

Could add a checkbox at the top that revealed email instead of username and could just power the whole thing with a paramter?
