### ISSUE TITLE
No obvious way to get to landing notebook

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#3]
When viewing a group that has a landing notebook, there is no obvious way to get to the actual Gallery page for that notebook or to run that notebook in Jupyter.  You have to toggle "view notebooks" and find it somewhere in the list (possibly on the next page), or you have to search for it.

**Comment by mcrutch** [comment]
Next to the title on the landing page there is now a  chain link icon with the hover text of "Navigate to Landing Page" which addresses this issue.
