### ISSUE TITLE
Cell output should be sanitized when displayed in the gallery

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/nbgallery#30]
Currently only admin-trusted notebooks may contain output.  However, that output could contain HTML that causes the rest of the page to render poorly.  It could also contain malicious HTML, but we assume that admins will apply the trusted tag judiciously.  Sanitizing cell output should be a pre-req for #22.

**Comment by mcrutch** [comment]
Define sanitization, and I don't mean this to be snark.  Output of the notebooks, if present, can have ALL sorts of stuff in it, including javascript, that might be completely necessary for it to display properly and by stripping it out we might effectively remove the value of including the output in the notebook.  So, I would love some deeper thoughts on this.

**Comment by mcrutch** [comment]
Decided we aren't going to expand sharing of notebook output anyway, so this is OBE.
