### ISSUE TITLE
Expose Group description on group pages most likely on the banner

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#301]
May take some finessing and edge case testing as real estate is limited

**Comment by mcrutch** [comment]
Real estate is so limited that even extremely long group names can cause issues where you can no longer edit the group name.  

![NBG_Group_Name_Description](https://user-images.githubusercontent.com/51446717/222153095-4d6054d2-07ae-4f74-969d-0df6434c750c.png)
