### ISSUE TITLE
Support markdown in description field?

### ISSUE THREAD

**Issue by jeffyjefflabs** [nbgallery/nbgallery#31]
It would be nice to include clickable links and basic formatting in notebook descriptions. However, I'm not sure we want to see descriptions with tables, h1 tags, etc.  I'm not sure if any markdown libraries can be configured to only allow certain features, or maybe we just assume users won't go crazy.

Alternately, we could just pass the description through an autolink filter to get clickable links, instead of doing full markdown.

**Comment by mcrutch** [comment]
redcarpet gem could be used for this: https://github.com/vmg/redcarpet
or HTML Pipeline https://github.com/jch/html-pipeline
We could use either as a full markdown solution or just to auto-linkify.

**Comment by mcrutch** [comment]
Forgot to close the ticket.  If GalleryConfig.markdown.description_enabled is set to true, Markdown will be enabled, but left off by default.
