### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by iankloo** [nbgallery/nbgallery#35]
I think I'm missing something fairly obvious, but how can I create/login as an admin user?  I am able to configure things enough to get to the nbgallery main page on a development server, but have no idea how to perform basic tasks such as user management.  

Can someone point me in the right direction?

**Comment by jeffyjefflabs** [comment]
You're not missing anything - that's something we should clean up, or at least document.

For the first admin user, right now you have to use either the mysql shell or the rails console.  You can either create the whole account that way, or just toggle the admin field on an account created via one of the omniauth integrations.

Once you have the first admin, that user can then access the `/users` endpoint, and you can toggle admin for other users from there.  But it looks like we don't link to `/users` from anywhere, so we should probably add that to the admin page (`/admin`, which will appear under the user silhouette pulldown menu for admin users).

**Comment by iankloo** [comment]
@jeffyjefflabs awesome, thanks for your quick response!  I should have been able to figure that out - I'm pretty new to Rails, so everything is just a little bit different.  Thanks again for your help with this.
