### ISSUE TITLE
Replace User Summary datepicker images

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#352]
For easier theme customizing, can't be using images, should replace with a background-color or images stored locally that look better with our themes

**Comment by mcrutch** [comment]
Fun fact, they don't even appear in production mode.  I now understand WHY...but swaping it out means replacing the entire icon sheet or doing a lot of serious style overrides.  For now, I am going to force them to appear at least

**Comment by mcrutch** [comment]
FYI -  In the running container, I did this - 

```/usr/src/nbgallery/public/assets# cp -R ../../vendor/assets/stylesheets/images ./```

**Comment by mcrutch** [comment]
Thought....since we already use glyphicons everywhere...bootstrap datepicker?  Since that uses glyphicons rather than images.
