### ISSUE TITLE
Cannot delete user with group membership: mysql2::error: Unknown column 'groups_users.' in 'where clause'

### ISSUE THREAD

**Issue by alexanghh** [nbgallery/nbgallery#357]
Hi,

I am getting error deleting a user who has a group membership with the following error:
ActiveRecord::StatementInvalid in UsersController#destory 
line: 196 `@viewed_user.destory`
Mysql2::Error: Unknown column 'groups_users.' in 'where clause': DELETE FROM `group_users` WHERE `groups_users`.`` = NULL

I had no issue deleting user without group membership. Had not tried deleting user with notebook.

Thanks.

**Comment by mcrutch** [comment]
So, were they only a member? or were they also an owner?  There is a bunch of auto-cascading delete stuff handle by ruby's built in active record stuff, and I just want to make sure I know all of the circumstances that lead up to this.

**Comment by mcrutch** [comment]
Found the problem....it is a built in rails thing I had to make a single primary key on the table for.
