### ISSUE TITLE
Deleting User Breaks Notebook if they Left a Comment

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#363]
Deleting a user who placed a comment on a notebook causes a 500 error to occur due to a nilClass referring a variable. Just needs a null check.

![deleting user who placed comment breaks notebook](https://user-images.githubusercontent.com/51969207/99821262-d146f100-2b1f-11eb-83c5-a6079f578436.PNG)

**Comment by mcrutch** [comment]
So, the proper way to fix this isn't in the commontator gem until 5.1.0 which requires at least rails 5.0 which would be a massive undertaking:
https://github.com/lml/commontator/blob/c767adb40c0d9a92279f0797ff5e5ffda2774281/lib/commontator/acts_as_commontator.rb
https://rubygems.org/gems/commontator/versions/5.1.0

`acts_as_commontator dependent: :destroy` would be in our code...IF we could do this...but we cannot

So...maybe a "before_destroy" on the user (and notebook) object to clean up the comments?
