### ISSUE TITLE
Run in Jupyter for Lab flaky....switch to SDI once Lab 3.0 is released.

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#373]

**Comment by jeffyjefflabs** [comment]
Just curious, what are you seeing?  I was wondering how well it would work with Lab's workspace system.

**Comment by mcrutch** [comment]
When I was testing with it running in just a singular container, it opened the notebook fine after loading the Jupyter Lab interface....Running in the hub environment, for some reason, it isn't opening the notebook most of the time.   I am kind of at a loss for why, so the SDI will be the way to go going forward.

**Comment by mcrutch** [comment]
So, I have been getting better behavior so I am going to leave it as is and if someone complains down the road we can re-address.
