### ISSUE TITLE
Remove Decline option for Change Request if you're the one that Created the Change Request

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#384]
If agreed, which need to discuss with team about it later is if we should hide the Approve and Decline buttons for users who are the ones that submitted it unless they are admins or at least hide the Decline button. The two red buttons causes a bit of confusion.

**Comment by jeffyjefflabs** [comment]
My two cents: if they are also an owner, then sure why not?  I think we've have some teams that do this with group-owned notebooks for code review.  I see it as similar to merging your own PR in your own project on GitHub.

**Comment by manfromjupyter** [comment]
@jeffyjefflabs Makes sense. I know they have Upload New Version if they were going to do it themselves but that makes sense. Would you be in favor of then just removing the "Decline" button for just the submitter (just so they don't see the double red buttons and get confused which to click). Side Note - those with edit access can't see the "Cancel" button so they already don't see the double red.

**Comment by jeffyjefflabs** [comment]
That seems reasonable - we don't keep long-term records of declined change requests except "fact of" in the clicks table, so in that situation Decline and Cancel are effectively the same.
