### ISSUE TITLE
Add rename option when a notebook with the same name already exists in Jupyter

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#4]
When sending a notebook from the Gallery to Jupyter, if a notebook with the same name already exists, give the user the option to rename the notebook rather than just overwriting it or canceling the action.

This is desirable in cases where notebooks have been forked or coincidentally are named the same on the Gallery.

**Comment by mcrutch** [comment]
You are afforded the opportunity to change the name rather than just cancel now.
