### ISSUE TITLE
Deleting User who is owner of group makes group... weird

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#403]
Group membership modal is just blank. Need to figure out what the solution is for this when owner of group gets deleted.
![deleting user that owns a group results in this](https://user-images.githubusercontent.com/51969207/103381047-a3f34880-4ab8-11eb-9161-fb2b2114ea72.PNG)

**Comment by mcrutch** [comment]
Pull request #405 said that groups owned by the person are deleted in the dialog.  So, what is actually happening?

**Comment by manfromjupyter** [comment]
@mcrutch Looks like member list of group is deleted, but the group itself is not deleted (or its owned notebooks). What to do from here is up for debate. Could go any way.

**Comment by mcrutch** [comment]
It is correct they aren't deleted, now that i think about it.  Can have multiple owners to a group.

Dialog about user deletion needs to be fixed
"Any groups where they are the sole owner will no longer be able to be modified" or something like that.

Above dialog needs to be updated to say "No Members" or something. (Going to play with that)

**Comment by mcrutch** [comment]
Thoughts?
![image](https://user-images.githubusercontent.com/51446717/105360522-abdd6e80-5bc6-11eb-987d-2b08c6c47129.png)

**Comment by mcrutch** [comment]
Also, how about this new wording for the delete user confirmation dialog?
![image](https://user-images.githubusercontent.com/51446717/105367120-1d6ceb00-5bce-11eb-8f3e-d7c2f05636ef.png)
