### ISSUE TITLE
Create 502 Bad Proxy Error Page

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#414]
Something along the lines of "NBGallery is currently down. This may be a temporary problem, please check back in a few minutes. If issues persist, please contact..." For the error image, could use the Star Wars one (the error 400, bad request meme) or the spaceship crashing one (the error 500 meme).

**Comment by mcrutch** [comment]
The bad proxy errors are not being generated by NBGallery, they are being generated by the upstream nginx proxy we use to forward the traffic.  No action here.
