### ISSUE TITLE
Need some tweaking on the tags tokenizer field of upload modal and maybe also search filtering (Accessibility)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#415]
If you have the tags "marketing", "test", and "data", it will read to screenreaders as "marketingx testx datax" because the delete icon is displayed/written in code as just the letter "x". Need to make the "x" aria-hidden and add screenreader only text and replace with "remove tag". While at it should ideally changed from a link (<a> tag) to a button.

**Comment by mcrutch** [comment]
Related #526

**Comment by mcrutch** [comment]
I think we are done here. Concur @manfromjupyter ?
