### ISSUE TITLE
Run in Jupyter modal needs to be pulled out of JS code for Accessibility and styling fixes

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#424]
Currently the modal is hardcoded. Proposal is to keep the scripting the same, but take out those hacks in place of a rails-made modal.

Need to consistency across the product, accessibility in the future, and one annoying bug for some people:
"long URLs wrap outside the table when multiple environments exists but none are default"

**Comment by mcrutch** [comment]
Work in progress. Old vs New
![image](https://user-images.githubusercontent.com/51446717/213277848-910af9e3-1c44-4621-a950-73cc80f44abd.png)

**Comment by manfromjupyter** [comment]
Oh my gawd, nice!

**Comment by mcrutch** [comment]
So far, 2 bootbox dialogs removed in the process as well.  Working my way through the Run in Jupyter workflow.
