### ISSUE TITLE
Add Search Filtering support for dates

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#425]
Add abilities to filter results in searches using before: and after: to only find notebooks created or last edited before or after a given MM/DD/YYYY date (but support a change in configurations to switch to DD/MM/YYYY for Europeans, etc).

PS. Reason for MM/DD/YYYY instead of any other or dashes or anything is because for accessibility users that is how dates are portrayed in fields across the site already to date).

**Comment by mcrutch** [comment]
SOLR does not support M/D/Y, only D/M/Y or Y-M-D.  We should really standardize with ISO-8601 across the site (Y-M-D) as that is internationally recognized and avoids weird problems.   So, make this Y-M-D, and we will work to convert the rest at a later date.

I have the back-end written, and it even pulls the tokens out in the UI, but you will have to come up with a UI to allow entering them. 

How it works:
Supported Field Names:
* updated
* created

Supported Operations:
* **field**:**value** (Between 00:00:00 and 23:59:59 on that date)
* **field**:>**value** (after 00:00:00 on that date)
* **field**:<**value** (before that date)

Now, if the user is feeling REALLY specific they could type:
`updated:>"2021-01-19 16:00"` 
And that would work, but the helper form doesn't have to support that.

See branch [date_range_search](https://github.com/nbgallery/nbgallery/tree/date_range_search) for the working back-end code.  Just need to pretty it up @manfromjupyter

**Comment by mcrutch** [comment]
So, here is a question....for invalid dates, it currently throws a 500 eroor that is a pass through from Solr screaming about the date. what do we want to do?
- Ignore the date
- Still throw a 500 error
- ignore the date AND throw a warning on the page (probably best)

**Comment by manfromjupyter** [comment]
When something doesn't match a current query, it just gets ignored or results no results. Could put it on the user and return no results?

**Comment by mcrutch** [comment]
The problem is if we pass it through to solr, solr will throw a 500 error rather than just no results (it barfs on invalid dates rather than just returning no results)
If we ignore it, well, the results would be too broad
if we ignore it, throw and error and no results, it might be best but figuring out how will be fun
Trying to fix the date is ambiguous
