### ISSUE TITLE
Add walk-through examples

### ISSUE THREAD

**Issue by stefanseefeld** [nbgallery/nbgallery#43]
I was looking for a way to share jupyter notebooks across a team, and discovered this project, which sounds like it's offering exactly the use-cases I'm looking for.
I have managed to run
```
docker-compose -f docker-compose.yml -f docker-compose-with-jupyter.yml up
```
and with that running can access a nbgallery portal at `http://localhost:3000/`. What I couldn't figure out is where to go from there. Notably:
* how can I add users to the system ?
* how can I connect the system to some notebook storage service (either a flat file system, or ideally some multi-user VCS such as git.

Are there existing docs that demonstrate these use-cases ? If not, would it be possible to add them ? (I'd be more than happy to help, once I understand the architecture a little better.)

**Comment by somedave** [comment]
@stefanseefeld sorry for not responding sooner - we could certainly do more to provide better documentation.  To quickly answer your questions, users should be able to create their own accounts.  An admin of the site can use the [settings here](https://github.com/nbgallery/nbgallery/blob/master/config/settings.yml#L136) to require admin approval of users who wish to create accounts, or only allow account registrations from a given e-mail domain.

By default nbgallery stores the notebooks locally, and [this config setting](https://github.com/nbgallery/nbgallery/blob/master/config/settings.yml#L30) define swhere nbgallery stores notebooks, and [this config setting](https://github.com/nbgallery/nbgallery/blob/master/config/settings.yml#L39) defines whether or not to enable nbgallery's internal git repository for version control.

Hope that helps get you started and we're happy to answer any questions (as we work to provide better documentation).  More information on how we use nbgallery ourselves can be [found here](https://www.youtube.com/watch?v=9qS1U-ySwzE&t=2s)

**Comment by jeffyjefflabs** [comment]
OAuth is also an option for user accounts - [some notes here](https://github.com/nbgallery/nbgallery/blob/master/docs/configuration.md#user-authentication-methods).

**Comment by stefanseefeld** [comment]
Thanks for the follow-up ! As I'm trying to explore `nbgallery` locally, on a machine without a valid associated domain, and no project ID created (yet) with any of the listed OAUTH login options, is there a way to (pre-)define users just for the sake of setting up and testing a prototype nbgallery instance ?
I'v been trying to follow the getting started guide, ran `docker-compose` with the proposed configs, but am stuck as I'm unable to register new users. It would be great if there was a way to hook up external authentication mechanisms so existing users (in a given domain) would have pre-generated accounts. Is something like that supported ?
Thanks,

**Comment by jeffyjefflabs** [comment]
Yes, with some additional code -- in fact that's exactly what we do in our production instance, which is part of the reason this aspect of the system is not well documented.  In our organization we connect to an external auth server, and that interface is implemented using our [extension system](https://github.com/nbgallery/nbgallery/blob/master/docs/extensions.md) to add a custom [Devise](https://github.com/plataformatec/devise) strategy.  We'll add to our documentation to-do list to publish a skeleton for how to do that.  (If you're using docker, you'd probably have to clone this repo, add your extension, and build your own version of the docker image.)

If you're using docker and just testing things out, you can set [some environment variables](https://github.com/nbgallery/nbgallery/blob/master/docs/configuration.md#creating-an-admin-user) to create an admin user/password at startup.  In practice we end up doing a lot of admin tasks through the rails console (you'd have to `docker exec` into the container), so the web UI doesn't have a nice admin dashboard yet.

**Comment by jeffyjefflabs** [comment]
Here's that skeleton for a custom Devise strategy: bdf57a5c319910425f3e50f795adf1cfb2ca743e

**Comment by mcrutch** [comment]
There is better documentation now for creating users initially including all the ways that is possible. (https://github.com/nbgallery/nbgallery/blob/master/docs/configuration.md)

For registering users through the regular process you will need an email server for the confirmation emails (but there is a fake one now available in the docker-compose.yml file if you take a look at it.)

Closing because there doesn't appear to be any other action on our end and the ticket is over a year without activity.
