### ISSUE TITLE
Enable Deprecation Status adding for all content owners and enable way to add links easily

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#441]
So we're ready for moving it from admins to editors and for the 2nd half, if we don't like it, then we can just elect not to do it and carry on with the first.

For background on the 2nd half @somedave thought that it'd be more user friendly and less markdown ridiculous (although said more elegantly) to just add another field, like the alternate notebooks one but for an external resource solely dedicated to the deprecation of a notebook. This could look like enabling an "Include external resource?" radio button, and then cause a title and url field to open up at the bottom of the current modal much like current External Resources. Alternative is we could  just enable markdown for it, but just wanted to add a solution for people with long links and make it dummy proof/consistent across all notebooks.

**Comment by manfromjupyter** [comment]
@mcrutch Wanted to get your take on the 2nd thing because we may want to get the 1st part in the next release. We don't currently enable markdown despite what I wrote above, but could maybe do that instead. Current pain is people just want to be able to add a link, maybe two.

**Comment by mcrutch** [comment]
I don't want to drop another 1-n metadata on top of something that is already metadata and will almost never be used.  Turn on markdown which I am pretty sure will automatically turn any link into a clickable URL even if it isn't in markdown.  
@somedave

**Comment by mcrutch** [comment]
BTW - There is already external resources that can be attached to the notebook itself if they don't like it in the deprecation status they can always link it that way.

**Comment by manfromjupyter** [comment]
@mcrutch Okie doke. That makes sense. For the ticket will just enable for non-admin notebook owners then.
