### ISSUE TITLE
Shares a notebook emails the email you already shared it with again

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#448]
Introduced to the user that reported it to use groups, but still poses a mild annoyance that can maybe addressed.

To reproduce:
1. Share notebook with a user.
2. Add new user to shared notebook and notice that the first user also gets emailed (again).

**Comment by mcrutch** [comment]
This was my experience:
* Share notebook with 3 users
* Those three users PLUS me get an email
* Share again, deleting one user adding another user
* The new user gets an email PLUS I get an email
* Share a notebook I don't own with 1 user
* I get an email as does the user

(Last two emails 
So the person DOING the sharing gets an email saying it was shared WITH them, every time they share.
![image](https://user-images.githubusercontent.com/51446717/107505742-23ba0b80-6b6b-11eb-8fd1-fd672e9a6b9e.png)

**Comment by mcrutch** [comment]
Looking at the code, it assumes the person doing the sharing is the owner. 
https://github.com/nbgallery/nbgallery/blob/main/app/controllers/notebooks_controller.rb#L320
Passes @user to NotebookMailer.shares

https://github.com/nbgallery/nbgallery/blob/main/app/mailers/notebook_mailer.rb#L4
Assumes second parameter is the notebook owner not the person doing the sharing

In reality, if Notebook Owner!=Active User, Notebook Owner should receive an email saying Active User shared the notebook with users x,y,z. IMO  But why should the active user get an email telling them that the notebook was shared with them?  So I would think leaving out the owner email on the BCC line would make the most sense, and OPTIONALLY doing a second email to the owner if owner!=user
https://github.com/nbgallery/nbgallery/blob/main/app/mailers/notebook_mailer.rb#L10

**Comment by manfromjupyter** [comment]
Oh good to know about the sharers all not being notified. I thought it was all of them. Thank you for testing that. I'm in favor of not sending the email to the person that initiated the share.

**Comment by mcrutch** [comment]
My only thought is...if the owner of the notebook is a person, and the person who shared the notebook wasn't the owner....we should probably notify the owner...but it would have to be a different email not the one that is currently sent out.  I will take out BCCing the active user...might document my other thoughts in another ticket.
