### ISSUE TITLE
Group Notebook Listing issues

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#452]
* Deprecated notebooks in a group are always shown regardless of the flag
* If the group has a landing page and you change the flags or sort, it goes back to the landing page and you have to click "View Notebooks" again.  If any search params are set should just show the notebook list by default (right now, appears to only do it if the page param is set

**Comment by manfromjupyter** [comment]
Shouldn't showing deprecated be used by default on those user and group sublistings because it's a very finite listing of notebooks already?

**Comment by mcrutch** [comment]
So this goes back to that whole conversation about overusing deprecation for things that shouldn't be deprecated.  The checkbox still appears, so if it appears it should work as advertised which the pull request makes it work properly and fixes the other issue with group views.  I guess I have to check user page now :-/

**Comment by manfromjupyter** [comment]
Might be the same for tags and language notebook listings as well

**Comment by mcrutch** [comment]
I will do users, tags, languages in a separate ticket
