### ISSUE TITLE
nbgallery not working in dcos cluster

### ISSUE THREAD

**Issue by ejunial** [nbgallery/nbgallery#46]
Enviroment:
dcos (10.255.0.33) cluster, all three services(mysql, solr and nbgallery) running in the same host and using docker container.

Issue:
Trying to get nbgallery(latest) to work along with mysql(5.7.21) and solr(8.1.1) i get the following error message, when uploading a notebook in nbgallery:

**_Error during failsafe response: Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit softCommit=\"false\"/>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP http://10.255.0.28:8983/solr/default/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}_**

Exactly the same setup works fine in my vagrant (local) virtual machine running:
**$docker-compose -f docker-compose.yml up**

Has anybody, any clues about this error? Any help would be much appreciated...

b r
/Junior

**Comment by jeffyjefflabs** [comment]
I don't have any experience with dcos but the error indicates that nbgallery can't reach solr.  I would suggest checking the networking within dcos, verify solr is actually up and running, and then make sure the nbgallery settings.yml has the right info for the solr server.

**Comment by mcrutch** [comment]
Closing for no follow-up in over a year
