### ISSUE TITLE
If 2 revisions of a notebook, but one is only a metadata change, table is broken

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#472]
If you upload a notebook, then make a metadata change only (possibly only with reviews turned off) you get a table that looks like this:
![image](https://user-images.githubusercontent.com/51446717/108882932-de69f500-75d2-11eb-9d71-39d9a002762b.png)

**Comment by manfromjupyter** [comment]
Weird. I definitely added handling for metadata in revisions. Will look into it... Maybe because the "compare" column is gone because of the single official version

**Comment by manfromjupyter** [comment]
For most recent being a metadata change, seeing this (NB id of 464 btw)
![metadata going over edge of table](https://user-images.githubusercontent.com/51969207/110035922-45418980-7d0a-11eb-9510-26b26e2ff9a7.PNG)

**Comment by mcrutch** [comment]
AFter your fix - 
![image](https://user-images.githubusercontent.com/51446717/110111549-807da000-7d7e-11eb-9ac8-c267dc728a1f.png)

**Comment by mcrutch** [comment]
Closed by #486
