### ISSUE TITLE
Not able to "Run in Jupyter" from nbgallery

### ISSUE THREAD

**Issue by ejunial** [nbgallery/nbgallery#48]
When trying to run a notebook in jupyter from my nbgallery App, i get an error:
-----------------
Run failed
Could not send notebook to https://172.17.0.4:443/. 
-----------------
The Jupyter server is running and i can run the notebook directly using https://172.17.0.4:443 in my browser . But when trying to do the same from nbgallery it does not work. (The "Jupyter Enviroment" is set to that same address)

Any clues or hints that could point me in the right direction would be much appreciated

B r
/Junior

**Comment by jeffyjefflabs** [comment]
Are you running nbgallery secure (https) also? The browser will block the cross-site Ajax used for the Run in Jupyter banner unless both are https or both are plain http.

**Comment by ejunial** [comment]
Nope.. See logs bellow...
[I 08:49:53.499 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 08:49:54.464 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 08:49:54.475 NotebookApp] Jupyter-nbGallery enabled!
[I 08:49:54.476 NotebookApp] Serving notebooks from local directory: /root
[I 08:49:54.476 NotebookApp] 0 active kernels
[I 08:49:54.476 NotebookApp] The Jupyter Notebook is running at:
[I 08:49:54.476 NotebookApp] http://0.0.0.0:80/
[I 08:49:54.476 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

So the server is up and running

I can access it from my browser using this address:
http://10.210.5.235:10063/tree

Then in nbgallery I put that address in as shown:
[cid:image001.png@01D52C0D.AA074DA0]

But when I press “Run in Jupyter”:
[cid:image002.png@01D52C0D.AA074DA0]

I get:
[cid:image003.png@01D52C0D.AA074DA0]

If I check the network tab in my browser’s web tool I see that the requested URL is different, and that of course that not work:
[cid:image004.png@01D52C0E.49F56180]

B r
/Junior

**Comment by jeffyjefflabs** [comment]
Your images didn't come through...

Just to double check, if you access Jupyter at `http://10.210.5.235:10063/tree` then the environment in nbgallery should be listed as `http://10.210.5.235:10063`

**Comment by ejunial** [comment]
I found the issue: it is related to the allow_origin property: c.NotebookApp.allow_origin. I had specified it with a star '*', because i'm runing in a cluster and nbgallery kan change host...But if i specify the host address of the nbgallery: c.NotebookApp.allow_origin = 'http://10.210.5.*:10061' then it works as expected....

**Comment by jeffyjefflabs** [comment]
Cool, glad you figured it out.  One thing to check if there are proxies in your setup is to make sure they're passing the various HTTP Origin headers through.  We saw something similar - I forget if we were trying allow_origin * or if we were using the allow_origin_pat setting, but ultimately our nbgallery has a stable location so we just went with that.
