### ISSUE TITLE
Shouldn't this be an X or Triangle rather than a Check?

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#481]
https://github.com/nbgallery/nbgallery/blob/2ab6e96f8d776ab3d3d58ae2db60748a49304b44/app/assets/javascripts/gallery.js.erb#L425

**Comment by manfromjupyter** [comment]
Oh hah, yep! Good catch. Also the margin below it should be reduced a little. Will fix it real quick
