### ISSUE TITLE
Stripping out sensitive content

### ISSUE THREAD

**Issue by psychemedia** [nbgallery/nbgallery#49]
From the public docs, one of the features of `nbgallery` seems to be stripping of outputs from shared notebooks:

> Since in many cases the data used within a notebook may be sensitive, the integration features automatically strip all notebook output before the notebook can be shared in nbgallery. This ensures output stays isolated to the user running the notebook, while ensuring the broadest possible sharing of the analytic itself.

To this end, I wonder if you have looked at Jupytext? Installing jupytext into an environment allows you to open text files (`.py`, `.Rmd` etc) with the Jupyter UI (document conversion is handled on the fly by Jupytext). You can run the file as if it were a notebook in the normal Jupyter notebook interface, and when you save the file the outputs are stripped out, which means that the code outputs need never be written to disk (I think; it would be good to see a professional security audit (beyond my ken) of how Jupytext does its stuff).

Jupytext also allows paring of documents, so you can pair eg py and ipynb document types so that when you open/edit either a py file or an ipynb file, the document is saved to both file formats (the ipynb doc includes the cell outputs, the eg py file doesn't).

Another nice feature is that Jupytext can recognise certain metadata attributes, such as one that allows you to mark a code cell as only being executable in a notebook view (either the live edit view, or the ipynb save), with the same code cell being commented out in the simple text file representations (eg a py file).

This means you can do things like create modules as py files, edit them via notebook UI, and include notebook-only code cells that might be used for documentation walkthroughs of the package, tests etc.

There's a related thread on the Jupyter discourse site [here](https://discourse.jupyter.org/t/jupyter-notebook-make-rawnbcell-temporarily-code-executable/1561).

Note: I'm not involved with the Jupytext project directly, though I am supportive of it. I've been looking for workflows that make sure I don't reveal personal info pulled from databases queried using Jupyter notebooks "by accident" by saving any of those details to disk and I think Jupytext may provide a candidate solution to that problem?

**Comment by jeffyjefflabs** [comment]
Sorry, missed this issue.  We have looked at jupytext; in fact we implemented [something similar](https://github.com/nbgallery/nbgallery/blob/master/docs/revisions.md#storage) for our internal git repo to keep the notebooks in a more git-friendly format.  Our deployment platform makes it hard to mix ruby and python, so we weren't able to use it directly.

nbconvert can also [clear output](https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#removing-cells-inputs-and-outputs); see also [this lively thread](https://github.com/jupyter/nbconvert/issues/637) for some other options.

**Comment by psychemedia** [comment]
@jeffyjefflabs I've been scrabbling together a list various nbcleaners and strippers for some time; I really need to tidy that list up and pop it somewhere.

I just mentioned the Jupytext route because the output stripping was actually a side-effect of being able to work with cleaner py/md document formats (which are editable *as notebooks* under Jupytext), which are both nicely diff-able text formats and allow easy loading as modules (eg in the case of py) or the creation of docs using eg Jupyter Book (in the case of md).

**Comment by manfromjupyter** [comment]
Closing as "Won't Fix"
