### ISSUE TITLE
Provide Feedback Fix undid itself it seems. Fix it

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#494]

**Comment by mcrutch** [comment]
???

**Comment by manfromjupyter** [comment]
Sorry, was just going to plan to fix it and explain once I realize all of it that is broken but by the looks of it, the provide feedback emails we made seem intact but the "Broken comments" field doesn't disappear when toggling between if we ran it or not. Need to investigate and fix.
