### ISSUE TITLE
Figure out how to pick a primary for running scheduled jobs in a clustered environment

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#497]
With database storage of notebooks becoming possible, you could now run multiple instances of NBG for load distribution of fail-over...but one must run the jobs and not the others....so how do we pick the winner without too much unnecessary overhead.

**Comment by mcrutch** [comment]
@jeffyjefflabs Thoughts?

**Comment by jeffyjefflabs** [comment]
This [SO question](https://stackoverflow.com/questions/4523185/how-to-elect-a-master-node-among-the-nodes-running-in-a-cluster) has some concrete suggestions for [leader election](https://en.wikipedia.org/wiki/Leader_election) (which I link to for reference but is mostly theory).

But the nbg job scheduler can run separately from the app, so what if *none* of the cluster instances the jobs, and instead you run the jobs from an extra standalone container?  How feasible is that with the docker setup?

**Comment by mcrutch** [comment]
I forgot about just toggling off the scheduled jobs which can even be done as an environment var passed to the container, so I even have a test setup running with two NBG behind one proxy sharing one database and one solr.  Notebooks are stored in the database.  So, this is an example of a load balanced OR redundant failover scenario for NBG, and then the only thing you have to worry about failing over is solr which you COULD run as a cluster, or just have search go down if you lose that node for a while.
