### ISSUE TITLE
Share Notebook with User can be shared with self (minor)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#499]
Not that big of an issue but users can share the notebook with themselves. Might want to disable that just so users don't feel they have to share it with themselves out of fear they will lose access by sharing with others or have multiple accounts and accidentally share with themselves forgetting they are already on the first.

**Comment by mcrutch** [comment]
Plausible workflow -> share with self, change owner

**Comment by manfromjupyter** [comment]
Confirmed. That's a legitimate use case. Just tried it too. Closing as "By Design"
