### ISSUE TITLE
Notebook testing

### ISSUE THREAD

**Issue by timkpaine** [nbgallery/nbgallery#50]
This may be relevant to this doc:
https://nbgallery.github.io/health_paper.html

https://github.com/timkpaine/jupyterlab_celltests

The main things addressed are:

"Our data security rules prevent “real” data from being captured in test suites, so authors would have to generate notional data."

"Automated tests typically have pre-defined inputs with expected outputs, while many of our notebooks process datasets that are obtained from external sources and may change over time or in response to user-specified parameters."

For us, financial data changes daily, and often systems go offline or are in different regions than where the tests are running, so you often need to mock underlying data. 

Elements of this (prerelease) post may also be interesting
https://medium.com/@t.paine154/production-notebooks-4ac545f80a9a

**Comment by somedave** [comment]
Thanks for this @timkpaine!   That medium post is very interesting and shares a lot with what we're thinking about for our "notebook as a service" production environment - more details on that [within this repo](https://github.com/nbgallery/dashboards)

**Comment by timkpaine** [comment]
@somedave it looks like our data entitlements models and targeted audiences are basically the same

@blink1073

**Comment by somedave** [comment]
Happy to chat further about our shared use-case and challenges. If you're interested what's the best way to reach you?

**Comment by timkpaine** [comment]
Let's set up a call, we can use blue jeans or something. Shoot me an email at timothy.k.paine@jpmorgan.com and I'll grab a few folks on our side

**Comment by blink1073** [comment]
Awesome, I am looking forward to chatting @somedave!

**Comment by timkpaine** [comment]
Will follow up on whatever formal channel we end up forming
