### ISSUE TITLE
Environment Select from Run doesn't support opening in Lab

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#504]
If you set an environment in LAB instead of classic and then set it as default, running in Jupyter will work but if you don't make any of them default and then manually select it when running, it won't work.

What looks like is happening is on the environments page the path is set to https://BLAH/jupyter/lab or https://BLAH/jupyter but when the little modal pops up asking which environment you want to run it in when one is not set as default, even if it's set to LAB, it will always only show the https://BLAH/jupyter format.

Stems from: #297 (merge #350)

**Comment by mcrutch** [comment]
The user can edit their environment to default to lab
If they go to lab first to register the environment, it will register it as default lab
Selecting at individual notebook run-time was not planned to be supported (if this ticket is what the concern is)
I have tested every possible way to find an actual bug:
* Multiple environments for the user
* None have a configured UI (as in all NULL in the database)
* Run, select environment, it works
* Set one to the default (and clear the configured UI from the database)
* Run, works (classic)
* Clear the default but set the UI to something (Classic/Lab)
* Run, select that environment, works
* Set that environment as default
* Works (launching appropriate UI)

**Comment by mcrutch** [comment]
BTW - That URL displayed doesn't even match what is used for classic (which appends /tree to the URL) so....that URL is just the base URL of the environment and doesn't expose anything about the execution environment.  It will either get /tree or /lab appended when the actual run happens.

**Comment by mcrutch** [comment]
So, is there clarification on this?  Is it a non-action or is something actually broken?

**Comment by manfromjupyter** [comment]
I'm going to be honest, I don't remember. I remember the many of us either having it work fine or feel it was broken. I will test it again and get back to this ticket. I think it may be a nonissue though and that it's just how we do our flasks, but will confirm

**Comment by manfromjupyter** [comment]
@mcrutch we figured out what the problem is. On line 50-54 of [run-in-jupyter.js.erb](https://github.com/nbgallery/nbgallery/blob/ddd297af9eaf03fb550b80089e73246a85fafcef/app/assets/javascripts/run_in_jupyter.js.erb#L51-L54), the `response[0].user_interface` should be `response[i].user_interface`. Otherwise the lab/classic preference will always be the first environment in the list.
