### ISSUE TITLE
Mimemagic gem got yanked

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#510]
https://github.com/rails/rails/issues/41750

Change to 0.3.6?

**Comment by manfromjupyter** [comment]
I use 0.3.2 but 0.3.6 may be fine.

**Comment by mcrutch** [comment]
0.3.2 NO LONGER EXISTS.  It was deleted.  Only two versions exist now. 0.3.6 and 0.4.0

**Comment by manfromjupyter** [comment]
Oh dear hah

**Comment by mcrutch** [comment]
https://github.com/mimemagicrb/mimemagic/issues/98
