### ISSUE TITLE
Support Toggling Private/Deprecated on Group Pages when all results are private and/or deprecated

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#522]
Visit a group with just private and/or deprecated notebooks you don't own (ex. note to self, the "Drop Bearz" group). Verify the page loads as having no results but the table allowing you to toggle deprecated and private notebooks still appears so you can reveal them.

**Comment by mcrutch** [comment]
# Old:
![image](https://user-images.githubusercontent.com/51446717/113278098-7aaca900-92af-11eb-976f-98afbdbdeba4.png)

# New:
![image](https://user-images.githubusercontent.com/51446717/113277831-243f6a80-92af-11eb-8897-300b3307cd36.png)
![image](https://user-images.githubusercontent.com/51446717/113277901-3a4d2b00-92af-11eb-92c2-87157ae20e28.png)
