### ISSUE TITLE
Change Request Emails tweak when owner leaves no comment

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#523]
Instead of saying `Owner comment: ""` when the comment field is left blank. Say either nothing or `Owner did not leave a comment.`

Also maybe "comments" should be "comment"? Idk

Current functionality (screenshot):
![owner comments on change requests](https://user-images.githubusercontent.com/51969207/113158204-952c4700-9209-11eb-87c9-e5b91e2a3268.PNG)

**Comment by mcrutch** [comment]
![image](https://user-images.githubusercontent.com/51446717/113282991-aa5eaf80-92b5-11eb-8376-4ffb73dc13f4.png)

**Comment by mcrutch** [comment]
Leaving as plural "Comments" because it feels more natural in context and they could make multiple comments in that field.
