### ISSUE TITLE
Look into adding dependencies section within Notebook metadata

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#531]
Need to bake it out more what exact kind of thing would be included in here. If less than 10% of notebooks would benefit form this, I don't see a benefit to it but yolo. Without much context, this is what has been imagined. A metadata section titled; "Dependencies:" followed up by a tag-like list of elements such as.... idk.... "requires EXCEL fil for upload", "required training X", required access to Marketing Database", etc.

OR could add it as a sections to the bottom of the notebook jumbotron that expands/collapses. Ex. move comments down to a tab dropdown, move Recommended notebooks over, add a Dependencies section, etc.

Original question: "It would be nice to add a bit more structure of optional fields to the description of the notebook. Having a specific place for people to list things like accesses to other departments or what databases to be able to run the notebook, if you need to upload a file, and if so what format in order for this to work. This would make it easier to see if a notebook is likely going to work for me."

**Comment by mcrutch** [comment]
I don't want to go too far down a bespoke implementation, but maybe pre-populating the description input for a notebook with a template that can be specified in the configuration?  Could even be pre-marked down.  

\#\# Purpose:
   \<Insert notebook Purpose Here>
\#\# Requirements:
   \<Any important pre-conditions, like specific input data or environment constraints>

**Comment by manfromjupyter** [comment]
Seems legit
