### ISSUE TITLE
Minor Fix with redirections on Change Request Controller (and potentially others)

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#546]
One of the users using the code for our site mentioned that on Line 103 of the change_controller.rb that they had change the `redirect_to(:back)` to `render json: { friendly_url: url_for(@change_request) }` because the former was redirected to http for them which then the browser would deny.

They said it might have something to do with their configs but wanted to let us know in case we wanted to fix it/might be experiencing it too.

User reports all of our `redirect_to(:back)`'s are doing this but this is just one such example. Might be worth seeing if we're seeing these issues as well or do it anyway if it breaks nothing.

**Comment by mcrutch** [comment]
I wonder if it is the way requests are being proxied through to the NBG server so it doesn't know SSL is in use upstream.

**Comment by mcrutch** [comment]
I know what the cause of this.  When you have it behind a proxy (likely that is doing SSL Termination) you need to add a header to upstream saying it is forwarding HTTPS so rails will make links HTTPS.  in nginx this is: proxy_set_header X-Forwarded-Proto https;
