### ISSUE TITLE
Add JSON endpoint for a notebook's runs, views, edits, stars, and edit history

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#551]
Currently can get to /notebook/{id}/metrics.json thanks to the notebook controller's metric's method, but would be nice to break those returns into unique methods out of the notebook model so that we can return json object.

**Comment by mcrutch** [comment]
What exactly do you want? Because we don't tell users WHO starred the notebook for example, so what does a new endpoint buy you that the metrics.json doesn't?
