### ISSUE TITLE
Resolve InvalidAuthenticityToken errors that occur

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#560]
Pretty sure 1-2% of people universally leave their computer sitting with their NBGallery tab open. When they get back it fires an Invalid Authenticity Token error because it's timed out and need to refresh. Upon refreshing they are fine, but so they don't lose any work and the site owners don't get email alerts anymore, set up a cron job to cause a pop up forcing them to refresh, blow up the page, or perhaps error catch the Invalid Authenticity Token error and make it a soft error that never triggers and instead just refreshes once to see if that fixes it?

**Comment by mcrutch** [comment]
Documenting here.  I think it is more that they leave Jupyter open and the token expires.

**Comment by manfromjupyter** [comment]
Researched needed into seeing how we'd want to handle this to soft fail for them.

**Comment by mild-bit** [comment]
#999 
- exception handling in the case of an invalid auth token
- error template for Invalid auth token

Setting up a way to refresh the page in the event of an Invalid auth token does sound like a good approach. But for now just add exception handling. InvalidAuthenticityToken will trigger an exception and display a message to the user to refresh the page. Closing this for now.
