### ISSUE TITLE
Provide Historical Feedback outside of email

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#568]
Pain:
- User can't see provided feedback over time unless sifting through emails. 
- User that recently acquired a notebook from somebody else doesn't know of it's pending feedback so doesn't know the community's gripes with it or just ideas to improve.
- Comments which linger and can be seen over time do not send emails so owners are not notified with a new comment is made.

Proposed Solution(s):
- Send emails for comments too.
- When submitting provide feedback form, include additional field such as "Include as comment as well for historical record-keeping purposes". If they select that and agree that the request or message does not violate our terms of service, then it will include it as a comment as well.

**Comment by mcrutch** [comment]
Comments are completely controlled by a ruby gem (commentator) so anything we do with comments should continue to tie through that so it depends on the capabilities of commentator.

**Comment by mcrutch** [comment]
feedback is already stored in the database we just don't expose it.
