### ISSUE TITLE
User summary not refreshing for "All time" if setting any parameters prior 

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#575]
On the User Summary page, when you set the parameters on the date picker and then click "Submit", hitting "All time" after it refreshers does not reset the user data. Removing the dates found in the picker and then hitting "All time" also doesn't reset it.

**Comment by mcrutch** [comment]
Worse than that, the date range doesn't seem to be working well at all. All-time, showed I did things..setting dates from 2001->the future showed NO STATS for me on my dev site.
