### ISSUE TITLE
Notebook counts found in header are not including deprecated notebooks

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#576]
Ex. In header it says I have 12 notebook but upon viewing them and enabled deprecated it revealed 15. Similarly when viewing starred notebooks, it shows 6 but I have 7 if including deprecated.

ALSO I understand not showing deprecated by default on searches but as it relates to stuff you own, considering most own less than 20 notebooks (to fit on one page), and there is a chance you won't know you have your name on something unsupported/broken, should we toggle that by default for just those views? 

If this is by design, then just let me know.  I understand in a previous discussion @mcrutch said "This is intended and is based on how those queries work by default now. Deprecation isn't used that much and if it gets to that point that so much is deprecated that it really matters, why would we clutter the user's default view with garbage". But I'm only throwing it out there because it has their name on it and it might remind them to eventually make it undeprecated or see if someone else can own it that can make it not... because if it's out of sight, it's out of mind completely.

If you still think it should be closed as "by design", I understand and will close it... Just thought I'd ask given this additional context.

**Comment by mcrutch** [comment]
Closing as by-design.
