### ISSUE TITLE
Update error message when uploading notebooks if Session Authenticity invalid

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#579]
When receiving an Invalid Authenticity token, the error says anything but. Only reason we know that is what it is is because we checked the logs. If we can catch for CRSF issues and can print accordingly it would be vastly more user friendly.

Error we get is "Error: 500 Internal Server Error If you are the administrator of this website, then please read this web applications log file and/or the web server's log file to find out what went wrong."

Ideally should be ex: "Error: There is an Invalid Authenticity token present in your session. Please refresh the page and try again." or something similar, idk

**Comment by mcrutch** [comment]
I will say, odds are, users aren't seeing this message because it is happening behind the scenes when they say save to gallery.  The first step does the staging in an ajax call and THEN redirects them in the browser.

**Comment by mild-bit** [comment]
resolved with #999
