### ISSUE TITLE
Error fetching information for the staged notebook

### ISSUE THREAD

**Issue by pffont** [nbgallery/nbgallery#652]
I'm trying to use docker-compose to run nbgallery, mysql, solr and jupyter using the compose files with the command: 

`$ docker-compose -f docker-compose.yml -f docker-compose-with-jupyter.yml up -d`

As of right now, I have NBGallery running at http://localhost:3000/ and an instance of jupyter at http://localhost:8888. However, when I create a new notebook in jupyter, click on the gallery tab, and click Upload to gallery I get a Gallery Communication Error and **There was an error fetching information for the staged notebook.** .

The jupyter instance has  these environments variables on compose file:

```
NBGALLERY_URL: http://localhost:3000
NBGALLERY_ENABLE_INSTRUMENTATION: 1
NBGALLERY_ENABLE_AUTODOWNLOAD: 1
```
Does anyone know how to solve it? Is this a configuration mistake?

**Comment by mcrutch** [comment]
Might have to wait till I merge #651...is NBGallery itself coming up ok? Are you logged in?  Check the "Network" terminal in the developers toolbar (F12 in most browsers) when you click the upload and see hat requests are going to nbgallery and what their response codes are.

**Comment by pffont** [comment]
Now, logged on NBGallery and with another tab in Jupyter, I can click on "Upload to NBGallery" and move for the "part 2" of the upload, but I'm getting this message after click on "upload":

**500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.**

**Comment by pffont** [comment]
I just rebuild all containers in a clean environment and this worked. 

Thanks!
