### ISSUE TITLE
docs/docker.md not working?

### ISSUE THREAD

**Issue by epoch1970** [nbgallery/nbgallery#658]
Hi. Thanks for NBgallery, it looks great. However I have some onboarding difficulties.

I followed instructions from this page: https://github.com/nbgallery/nbgallery/blob/main/docs/docker.md
ONLY the mandatory instructions. Nothing optional.
After that, `docker-compose -f docker-compose.yml -f docker-compose-with-jupyter.yml up` yields (after some startup time) an empty nbgallery. 

From JupyterLab the "upload to NBgallery" button appears to be dead.
From the NBgallery web UI, I cannot login nor create a user. 

I activated the "fake snmp" server in the compose file; I can see its web interface but apparently it receives no email at all.
I created the admin user hoping to work around the issue temporarily. The account is not usable in the UI.

Is it me?

**Comment by mcrutch** [comment]
Sorry for the delayed response.  Will look into this as soon as we can

**Comment by epoch1970** [comment]
Thank you for following up. 
I think I was "running in localhost"; I strictly followed the  page Docker.md. Docker was running in Win10/wsl2, on a recent, low-end laptop, that might be not ideal?
After some blunt surgery of the config file I somehow managed to publish a notebook to nbgallery (so login worked at least once), but was never able to retrieve it later from the gallery. Push ok, pull ko.
I will possibly try again from fresh code as you advise, but not immediately. Thanks again.
