### ISSUE TITLE
Drop support for Internet Explorer 11

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#664]
Might need to confirm if my JS was enabled for my Internet Explorer, but pretty sure it was working for some things.

Anyway, I just tested it and realize none of the app supports Internet Explorer. Currently we've been blocking Internet Explorer when not IE11 or when in compatibility mode, but due to tooltips, onclicks, expansion/collapse of elements, and editing of title/description not working, I think it's time we drop support for it, or else it'll take an immense amount of work to support.

Thoughts? @mcrutch

**Comment by mcrutch** [comment]
IE reached EOL June 2022. We actually need to revisit the modern browser stuff though because it triggers sometimes when things are hitting an API.

**Comment by mcrutch** [comment]
* Update to a more modern version of the Browser Gem
* Drop IE officially
* Only trigger if not making a JSON request
