### ISSUE TITLE
Error on modals allows scrolling on the page itself, not the modal to fix the issue

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#671]
Trigger big error on a modal (like one that would cause a Bad Notebook) then try scrolling. The modal needs to be the only thing that moves up and down, not the page.

**Comment by mcrutch** [comment]
Why are we displaying HTML error pages in modals anyway, rather than just having JSON return with concise message for all error modals?  That is the real problem.

**Comment by manfromjupyter** [comment]
Will be fixed with #798 (as well as other things) so closing this one. By having the consistent format of errors and not reloading pages that the issue can be fixed, this scrolling issue won't happen. For issues where we plan on reloading the page, this scrolling is not applicable.
