### ISSUE TITLE
Search box gets "busy"

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#685]
This is a bit of chaos
![image](https://user-images.githubusercontent.com/51446717/183075884-460353db-1043-47f4-ae20-6cb7f2270139.png)

**Comment by mcrutch** [comment]
Also, clicking on the 'i' to bring up the info box causes the tool tip to flash on the screen.  I am working off of the type-button-audit branch which is now up-to-date with main

**Comment by manfromjupyter** [comment]
Wow that's quite a pickle you got yourself in there lol. I will take a look and see what our options are.

**Comment by manfromjupyter** [comment]
Can no longer reproduce. Chrome may have fixed the issue that no longer having focus on exactly the input role=search element causes it to no longer appear. By focusing on the help "i", the search autocomplete disappears. On focusing on the search autocomplete, the help "i" tooltip goes away. Only way you can reproduce this now is if you forced the focus of the help "i" using the Inspect/Dev Tools and then went to show search autocomplete.

**Comment by mcrutch** [comment]
Still happens, but maybe with #873 we can change how the icons work or their location to make this OBE
![image](https://github.com/nbgallery/nbgallery/assets/51446717/9fbf4947-24a7-4698-9241-a7d6c0788c74)
