### ISSUE TITLE
Markdown Rendering CSS Problem with <h1>

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#693]
If you have the following markdown
```markdown
# heading
* long list item to show overlap
* list item
* list item
```
You get Overlap in the display when description_markdown is true
![image](https://user-images.githubusercontent.com/51446717/187679468-f9b28077-0d1c-4050-9774-662df7446974.png)

**Comment by manfromjupyter** [comment]
@mcrutch I will support it but for accessibility they shouldn't be adding <h1>s anyway. The true and only H1 should be the Notebook title on the page. Unless users plan on extracting their notebook as an HTML file or PDF or something, the Jupyter app and our app will both have that H1 for them at the top of their notebook.
