### ISSUE TITLE
Add SSL cert for MySQL Server

### ISSUE THREAD

**Issue by iamroku** [nbgallery/nbgallery#696]
Hi there 

Hoping someone can assist or guide me on how to add a custom SSL cert for MySQL. I Would like to use a managed MySQL database and SSL is a requirement. I've never worked with Ruby before so still trying to figure out all the pieces, any guidance or direction here would be greatly appreciated

**Comment by C-Oliver** [comment]
This is something I am also interested in! Guidance would be greatly appreciated!

**Comment by mcrutch** [comment]
I think this is what you need: https://makandracards.com/makandra/1701-use-ssl-for-amazon-rds-mysql-and-your-rails-app

> To make your Rails application use SSL, modify config/database.yml and add this:
> sslca: /path/to/mysql-ssl-ca-cert.pem

I have not had time/opportunity to test this

**Comment by iamroku** [comment]
Thank you - will update and contribute if u believe this is a valuable addition

**Comment by mcrutch** [comment]
If that worked, worth putting it in as a commented out line in config/database.yml.

**Comment by mcrutch** [comment]
@iamroku Did adding that sslca parameter solve the problem?  If so I can add documentation and/or a well placed comment.

**Comment by ScratZa** [comment]
Hi there - I can confirm that your suggestion works 

I essentially added this to the db config   
sslca: cert/cert.pem

Made sure to copy that folder in the docker build and it was golden
