### ISSUE TITLE
Attempting to Upgrade

### ISSUE THREAD

**Issue by ScratZa** [nbgallery/nbgallery#709]
Hi 

Attempting to upgrade gallery to a more up to date rails and ruby version (managed to get it going on Ruby 2.7 and rails 5.0 however updating to 5.1 seems to pretty much break anything related to commentator . 

From what i can see its related to the thread ID not being being populated in most cases - can see thread is nil after a NB save - any idea what could be causing this? 
If not ill attempt to figure it out and hopefully get a PR in

**Comment by mcrutch** [comment]
I would love to just know what you did to get it working in Rails 5, we were going to look into that lift and shift if we got some time, but it hasn't hit our radar and would love a PR for any changes you needed for that.

**Comment by ScratZa** [comment]
Yea sure - managed to sort out most issues i believe - but not sure how many bugs are around might need your help in cleaning up the PR to be honest. Completely new to ruby. 

Will try get that PR out today

**Comment by ScratZa** [comment]
Not sure what it is but cant get nmatrix to install on ruby 2.7 
`#6 6.567 Building native extensions. This could take a while...
#6 6.751 /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:175: warning: conflicting chdir during another chdir block
#6 6.786 ERROR:  While executing gem ... (Gem::Ext::BuildError)
#6 6.786     ERROR: Failed to build gem native extension.
#6 6.786 
#6 6.786     current directory: /usr/local/bundle/gems/nmatrix-0.2.4/ext/nmatrix
#6 6.786 /usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r ./siteconf20221202-7-1ddnw64.rb extconf.rb
#6 6.786 checking for apparent GNU g++ binary with C++0x/C++11 support... *** extconf.rb failed ***
#6 6.786 Could not create Makefile due to some reason, probably lack of necessary
#6 6.786 libraries and/or headers.  Check the mkmf.log file for more details.  You may
#6 6.786 need configuration options.
#6 6.786 
#6 6.786 Provided configuration options:
#6 6.786        --with-opt-dir
#6 6.786        --without-opt-dir
#6 6.786        --with-opt-include
#6 6.786        --without-opt-include=${opt-dir}/include
#6 6.786        --with-opt-lib
#6 6.786        --without-opt-lib=${opt-dir}/lib
#6 6.786        --with-make-prog
#6 6.786        --without-make-prog
#6 6.786        --srcdir=.
#6 6.786        --curdir
#6 6.786        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
#6 6.786 /usr/local/bundle/gems/nmatrix-0.2.4/lib/nmatrix/mkmf.rb:74:in `<top (required)>': You need a version of g++ which supports -std=c++0x or -std=c++11. If you're on a Mac and using Homebrew, we recommend using mac-brew-gcc.sh to install a more recent g++. (RuntimeError)
#6 6.786        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
#6 6.786        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
#6 6.786        from extconf.rb:28:in `<main>'
#6 6.786 
#6 6.786 extconf failed, exit code 1
#6 6.786 
#6 6.786 Gem files will remain installed in /usr/local/bundle/gems/nmatrix-0.2.4 for inspection.
#6 6.786 Results logged to /usr/local/bundle/extensions/x86_64-linux/2.7.0/nmatrix-0.2.4/gem_make.out`

**Comment by ScratZa** [comment]
if u have any ideas  - let me know - strangely enough locally on wsl it will build fine - installed ruby with rbenv 

When we go to the docker builds above error shows up for nmatrix
