### ISSUE TITLE
Approved, declined or cancel requests feature not working

### ISSUE THREAD

**Issue by spark2k06** [nbgallery/nbgallery#73]
The Submit button has no effect, I can only press Cancel:

![image](https://user-images.githubusercontent.com/3509674/69427718-1f1ff200-0d30-11ea-9b84-2c4782ef9551.png)

In the Master branch I see a single reference to 'accept_change_request_path', 'decline_change_request_path' and 'cancel_change_request_path' throughout the nbgallery source code, such that:

`var url = '#{cancel_change_request_path(@change_request)}'`

I'm missing something?

**Comment by mcrutch** [comment]
This should be fixed in the Accessibility-6 branch which I am working my way through the review now.  Some of the submit buttons ended up outside of the form by accident.

**Comment by mcrutch** [comment]
Tested and confirmed #71 will resolve this issue.

**Comment by spark2k06** [comment]
Viewed! Thanks for the information, I close the issue.
