### ISSUE TITLE
Worth/possible to only use one of glyphicon/font acid icons?

### ISSUE THREAD

**Issue by mcrutch** [nbgallery/nbgallery#765]
We have both scattered all over the place.  I don't think glyphicons are complete enough for our purposes, but could fa icons be?

**Comment by manfromjupyter** [comment]
In my opinion, yes. It's not a perfect match but different interpretations/replacements could be used.

I remember mentioning this issue a while ago (like 2 years ago) that we should use only one but in my research of it I found that the icons are just not as pretty than the current glyphicons used and we would have to make some unfavorable replacements that might confuse people. This is still possible and if you would indeed like to pursuit this I'm happy to make a comparison list of all icons and the font-awesome replacements for them I think should they should be replaced by. After that we can tackle this icon by icon of the ones that aren't a perfect eye-ball to eye-ball replacement for example and those we might need to find a slight alternative for until we we're happy with all of them.

**Comment by mcrutch** [comment]
Yeah, I feel like over time everything including the kitchen sink were thrown is as dependencies, and it is a little busy so cutting down on dependencies and duplication where we can makes things more sustainable long-term

**Comment by mcrutch** [comment]
what about fork-icons?  it replaces font awesome as a drop in replacement with more opens as well.  We could rip out both glyphicons and font-awesome and manually inject fork-awesome.  There is even a Jupyter icon in fork-awesome.

**Comment by manfromjupyter** [comment]
Wow. How have I never heard of that. I like it... A lot. We wouldn't even have to change a lot of our code. example syntax of fork-awesome:
`<i class="fa fa-file-o" aria-hidden="true"></i>`
