### ISSUE TITLE
Cannot log in with email address

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#8]
No indication in the logs why it doesn't work :(

**Comment by phungc** [comment]
Login with email works for me but login with user_name fails.

Make sure columns "approved" is set to 1 and "confirmed_at" is not null in "users" table.

**Comment by jeffyjefflabs** [comment]
@phungc's comment is correct.  We need to verify that the registration confirmation email workflow properly sets those two fields in the user object.

**Comment by mcrutch** [comment]
See #249, I think this was a problem with documentation and email server configuration.  Account activation emails work fine if those are configured properly and some updates were made to the docs to clarify what needed to be set for email and code changes made to support an email server that doesn't require credentials.
