### ISSUE TITLE
Recommended Notebooks tab hangs on a 500 error, caused by mySQL setting

### ISSUE THREAD

**Issue by BrendanPC** [nbgallery/nbgallery#810]
After installing the latest image and going to the Recommended tab, the page hangs trying to load. The query used to build recommendations seems to go against the default mySQL settings (ONLY_FULL_GROUP_BY is a default as of  mySQL 5.7.5).

Related StackOverflow question: https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc

Changing the ONLY_FULL_GROUP_BY setting as described in the link, worked to fix the issue.

**Converted backticks to single-quotes to avoid GitHub weird formatting:**
I, [2023-02-16T17:48:16.178466 #47]  INFO -- : Started GET "/home_notebooks?type=suggested" for x.x.x.x at 2023-02-16 17:48:16 +0000
I, [2023-02-16T17:48:16.179906 #47]  INFO -- : Processing by StaticPagesController#home_notebooks as */*
I, [2023-02-16T17:48:16.179972 #47]  INFO -- :   Parameters: {"type"=>"suggested"}
D, [2023-02-16T17:48:16.181988 #47] DEBUG -- :   User Load (0.4ms)  SELECT 'users'.* FROM 'users' WHERE 'users'.'id' = 1 ORDER BY 'users'.'id' ASC LIMIT 1
D, [2023-02-16T17:48:16.183858 #47] DEBUG -- :   User Exists? (0.4ms)  SELECT 1 AS one FROM 'users' WHERE LOWER('users'.'email') = LOWER('email@example.com') AND 'users'.'id' != 1 LIMIT 1
D, [2023-02-16T17:48:16.184742 #47] DEBUG -- :   User Exists? (0.3ms)  SELECT 1 AS one FROM 'users' WHERE 'users'.'user_name' = 'admin' AND 'users'.'id' != 1 LIMIT 1
D, [2023-02-16T17:48:16.185660 #47] DEBUG -- :   SiteWarning Load (0.3ms)  SELECT 'site_warnings'.* FROM 'site_warnings' ORDER BY 'site_warnings'.'id' DESC LIMIT 1
D, [2023-02-16T17:48:16.187855 #47] DEBUG -- :   Click Load (0.4ms)  SELECT notebook_id, SUM(IF(action='executed notebook',1.0,0.5)) AS score FROM 'clicks' WHERE 'clicks'.'user_id' = 1 AND (updated_at > '2022-11-18 17:48:16.186935') GROUP BY 'clicks'.'notebook_id'
D, [2023-02-16T17:48:16.189152 #47] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM 'suggested_notebooks' WHERE 'suggested_notebooks'.'user_id' = 1
D, [2023-02-16T17:48:16.190472 #47] DEBUG -- :   Click Load (0.5ms)  SELECT 'clicks'.* FROM 'clicks' WHERE 'clicks'.'user_id' = 1 AND (updated_at > '2023-01-17 17:48:16.189345') GROUP BY 'clicks'.'notebook_id'
I, [2023-02-16T17:48:16.190732 #47]  INFO -- : Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.9ms | Allocations: 3390)
F, [2023-02-16T17:48:16.191301 #47] FATAL -- :
ActiveRecord::StatementInvalid (Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gallery.clicks.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by):
  app/models/suggested_notebook.rb:45:in 'map'
  app/models/suggested_notebook.rb:45:in 'user_defeats'
  app/models/suggested_notebook.rb:55:in 'compute_for'
  app/models/user.rb:526:in 'compute_recommendations'
  app/models/user.rb:536:in 'notebook_recommendations'
  app/controllers/application_controller.rb:370:in 'home_notebooks'
I, [2023-02-16T17:48:16.191759 #47]  INFO -- : Processing by Gaffe::ErrorsController#show as */*
I, [2023-02-16T17:48:16.191808 #47]  INFO -- :   Parameters: {"type"=>"suggested"}
D, [2023-02-16T17:48:16.192697 #47] DEBUG -- :   CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM 'users' WHERE LOWER('users'.'email') = LOWER('email@example.com') AND 'users'.'id' != 1 LIMIT 1
D, [2023-02-16T17:48:16.193111 #47] DEBUG -- :   CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM 'users' WHERE 'users'.'user_name' = 'admin' AND 'users'.'id' != 1 LIMIT 1
D, [2023-02-16T17:48:16.193589 #47] DEBUG -- :   CACHE SiteWarning Load (0.0ms)  SELECT 'site_warnings'.* FROM 'site_warnings' ORDER BY 'site_warnings'.'id' DESC LIMIT 1
D, [2023-02-16T17:48:16.194566 #47] DEBUG -- :   Rendering layout layouts/error.slim
D, [2023-02-16T17:48:16.194655 #47] DEBUG -- :   Rendering errors/internal_server_error.slim within layouts/error
I, [2023-02-16T17:48:16.194873 #47]  INFO -- :   Rendered errors/internal_server_error.slim within layouts/error (Duration: 0.2ms | Allocations: 62)
I, [2023-02-16T17:48:16.195294 #47]  INFO -- :   Rendered layout layouts/error.slim (Duration: 0.7ms | Allocations: 312)
I, [2023-02-16T17:48:16.195541 #47]  INFO -- : Completed 500 Internal Server Error in 4ms (Views: 1.2ms | ActiveRecord: 0.1ms | Solr: 0.0ms | Allocations: 2186)

**Comment by mcrutch** [comment]
Related
https://stackoverflow.com/questions/41355634/incompatible-with-sql-mode-only-full-group-by-in-mysql

**Comment by mcrutch** [comment]
This is the line that block that needs rework.  Adding a .select might solve it. 
https://github.com/nbgallery/nbgallery/blob/main/app/models/suggested_notebook.rb#L42

This was due to the effort to remove the deprecated .pluck and this didn't pop up in testing bug I am guessing the overnight job for suggestions just didn't run against my user possibly which caused the discrepancy.

**Comment by mcrutch** [comment]
Might have a bunch of other places this is affected, need to try and replicate.  Although our database in our dev environment is 5.7.latest based, it has 5.7.0 defaults it seems.  Changing the default to more current now so I can better verify this.

**Comment by mcrutch** [comment]
Couldn't find any other place this caused problems.  But our test environment will now show this in the future.
