### ISSUE TITLE
Tag Add/Edit/Delete Refactor

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#850]
1. Support persons with disabilities
2. Fix issue where user adds text to tag field to add but submits form.

Ideally split up the tags into 2 things. Place to add and display of the tags (not in the same field).

**Comment by mcrutch** [comment]
Relates to #415

**Comment by mcrutch** [comment]
Does #935 resolve this in your mind @manfromjupyter ?

**Comment by manfromjupyter** [comment]
@mcrutch sorry for the delay. It's definitely an improvement but I see the following things that should probably get addressed if it's even possible.

My quick summary:

## All Tag Fields
1. When a tag is deleted or added we need a screenreader alert makeScreenreaderAlert() or whatever saying as such. 
2. Within the label of that additional "Enter Tags here" field, we should mention to screenreaders, "Enter space key or enter key to add tags"
3. On the tags visual/deletion field, it should read to screenreaders in the label that Enter or ESC or whatever will delete tags. I know we added text to the x button but they can still accidentally delete with the backspace character or while reading the tags itself could press "ENTER" which would delete them.

## Tag Field just on Upload Modals
1. aria-label is "undefined" for some reason so it reads "Undefined edit Enter tags here type of text". 

## Tag Field just on Notebooks
1. No placeholder text
