### ISSUE TITLE
Replace ".hide" with hidden

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#853]
.hide class only hides things visually but not for blind and low visions people using assistive technologies (screen readers).

`hidden` ex. `<p class="class1" hidden>Test</p>` will hide it both visually and for screen readers.

Places where we are applying .hide should instead be replaced with `hidden` and JS instead of adding/removing said class should be apping removing `.prop('hidden',true')`

## While at it
Places were we are using `style="display;none"` and using JS to toggle this, should also be replaced with this property. Hidden has been supported since one of the first few versions of Chrome, Edge, and Firefox and is the preferred cleaner way to do this: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden

**Comment by mcrutch** [comment]
Some of the display:none stuff is baked into bootstrap dropdowns and would take a lot of effort to override and undo.
