### ISSUE TITLE
Add Support for an empty search page

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#873]
1. Searching nothing should send you to a blank search page where instead of results explains how to do searches, use filters in the UI or manually, use `||` (ORs) or `&&` (Ands), or other kind of tricks we currently have with SOLR.
2. Link to this should be included in the header question mark dropdown.
3. Either clicking the info icon on the search bars sends you to this instead OR is entirely removed in favor of a 
`"Interested in advanced searching?"`

**Comment by mcrutch** [comment]
Closed By #879
