### ISSUE TITLE
Search Issues + New Features 

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#877]
## Fix
1. Searching for something with underscores causes next load of page to render the preloaded search text without the underscore. Searching again may change the results because that underscore before will not be searching for a space between the characters.

## Implement
1. Add support for searching form multiple words with include quotes. AKA, give us ability to escape our quotes in searches.
2. (Maybe?) Add support for enabling Matching Case so we can exclude searches where our words without the Uppercase or Lowercase we specified isn't applicable.
3. Stuff from #873 ?

**Comment by mcrutch** [comment]
Search for quotes in quotes is not a thing because the tokenizer doesn't allow it
Can't have both Case insensitive and Case Sensitive Search
The Empty Search page is another issue that work is being done against
Closing thi sone.
