### ISSUE TITLE
`Redirecting to edit path for user` when going to nbgallery

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#887]
Hi there, 

   I'm trying to upgrade our nbgallery deployment from ruby 2.4 -> ruby 2.7, and rails 4.2 -> rails 6.0, but when we go to nbgallery it just infinitely redirects to the edit path for user. This is in the production.logs for each network call: 
```
Started GET "/users/-<REDACTED USERNAME>/edit" for 127.0.0.1 at 2023-08-02 15:36:38 +0000
I, [2023-08-02T15:36:38.198895 #44]  INFO -- : Processing by UsersController#edit as HTML
I, [2023-08-02T15:36:38.198955 #44]  INFO -- :   Parameters: {"id"=>"-<REDACTED USERNAME>"}
D, [2023-08-02T15:36:38.201248 #44] DEBUG -- :   User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IS NULL ORDER BY `users`.`id` ASC LIMIT 1
D, [2023-08-02T15:36:38.322516 #44] DEBUG -- :   User Load (0.7ms)  SELECT `users`.* FROM `users` WHERE `users`.`email` = '<REDACTED USERNAME>' ORDER BY `users`.`id` ASC LIMIT 1
D, [2023-08-02T15:36:38.433004 #44] DEBUG -- :   TRANSACTION (0.5ms)  BEGIN
D, [2023-08-02T15:36:38.433755 #44] DEBUG -- :   User Exists? (0.6ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = '<REDACTED USERNAME>' LIMIT 1
D, [2023-08-02T15:36:38.434954 #44] DEBUG -- :   User Exists? (0.3ms)  SELECT 1 AS one FROM `users` WHERE LOWER(`users`.`email`) = LOWER('<REDACTED USERNAME>') LIMIT 1
D, [2023-08-02T15:36:38.435642 #44] DEBUG -- :   User Exists? (0.3ms)  SELECT 1 AS one FROM `users` WHERE `users`.`user_name` = '<REDACTED USERNAME>' LIMIT 1
D, [2023-08-02T15:36:38.436165 #44] DEBUG -- :   TRANSACTION (0.2ms)  ROLLBACK
D, [2023-08-02T15:36:38.437765 #44] DEBUG -- :   User Exists? (0.5ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = '<REDACTED USERNAME>' LIMIT 1
D, [2023-08-02T15:36:38.438623 #44] DEBUG -- :   User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE LOWER(`users`.`email`) = LOWER('<REDACTED USERNAME>') LIMIT 1
D, [2023-08-02T15:36:38.439225 #44] DEBUG -- :   User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`user_name` = '<REDACTED USERNAME>' LIMIT 1
D, [2023-08-02T15:36:38.439542 #44] DEBUG -- : Redirecting to edit path for user
I, [2023-08-02T15:36:38.440025 #44]  INFO -- : Redirected to https://nbgallery<REDACTED URL>/users/-<REDACTED USERNAME>/edit
I, [2023-08-02T15:36:38.440137 #44]  INFO -- : Completed 302 Found in 241ms (ActiveRecord: 4.0ms | Allocations: 4652)
```
Any idea what might've caused this and what I could do to fix it?

**Comment by mcrutch** [comment]
Is the user not "confirmed?"  or missing any required fields?   Code implies maybe they are missing a user_name?  Also from the code:
https://github.com/nbgallery/nbgallery/blob/cd6116dd11cf417d17d900aaf511a524d9329260/app/controllers/application_controller.rb#L474C1-L487C6
```
    #Only redirect if you are not trying to edit yourself
    #Otherwise infinite redirect loop
 ```

**Comment by mcrutch** [comment]
Specifically, this is getting triggered - rescue_from User::MissingRequiredFields, with: :must_set_required_fields
so the user is missing required fields.  That gets called from set_user
https://github.com/nbgallery/nbgallery/blob/cd6116dd11cf417d17d900aaf511a524d9329260/app/controllers/application_controller.rb#L78

**Comment by cccs-cat001** [comment]
we do set the user_name to be the same as the email, and the `confirmed_at` field is set to the date they first logged in. 

Are migrations automatically applied when the app runs? Maybe I'm missing some migrations?

**Comment by mcrutch** [comment]
If you are using our container, it has hte line, otherwise you have to make sure you run the migrate command
https://github.com/nbgallery/nbgallery/blob/cd6116dd11cf417d17d900aaf511a524d9329260/docker-entrypoint.sh#L52

**Comment by cccs-cat001** [comment]
hmm alright so that's not it, we're using that entrypoint.

**Comment by mcrutch** [comment]
Any way to completely clear out your session and try logging in from scratch and see what happens?  Check the record in the database for that logged in user and double check all the fields that are required are populated.   This is the validation stuff:
https://github.com/nbgallery/nbgallery/blob/cd6116dd11cf417d17d900aaf511a524d9329260/app/models/user.rb#L115C2-L125

**Comment by cccs-cat001** [comment]
Ah ok so I think my custom auth extension isn't being applied, it's supposed to update those necessary user fields but it isn't. I had enabled `config.autoloader = :classic` in the application.rb file, in order to avoid a zeitwerk error I was facing.. but perhaps it's better to face that issue head-on lol

When I run it without that config, zeitwerk errors out with 
```
/usr/src/nbgallery/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `const_get': uninitialized constant Oidc (NameError)  
```
the extension is added to the `/usr/src/nbgallery/extensions` directory: 
```
root@af81193d8f67:/usr/src/nbgallery/extensions# tree
.
├── oidc
│   ├── devise
│   │   └── strategies
│   │       └── oidc.rb
│   └── oidc.rb
└── propose_org_as_tag
    ├── propose_org_as_tag.rb
    └── propose_org_as_tag.yml

4 directories, 4 files
```
and the `oidc/devise/strategies/oidc.rb file is defined with: 
```ruby
module Devise
    module Strategies
        class Oidc < Base
            def authenticate!
                {{bunch of authentication}}
            end
            # Tells Devise that this strategy is enabled
            def valid?
                true
            end
        end
    end
end
```
So I'm really not sure why zeitwerk has an issue with this extension. Might you know?

**Comment by cccs-cat001** [comment]
right, so I think I fixed my zeitwerk issue by changing https://github.com/nbgallery/nbgallery/blob/cd6116dd11cf417d17d900aaf511a524d9329260/config/application.rb#L104 to be 
```ruby
      config.autoload_paths += Dir[File.join(dir, '*')]
```
(eager_load_paths -> autoload_paths is all I did)

But this redirect issue is back... 

I deleted my user from the DB so I can start fresh, and it doesn't fall into a redirect loop, but it does give me this warning: 
![image](https://github.com/nbgallery/nbgallery/assets/56204545/de8d64cc-4e4c-4d0e-93b5-0a4df255d259)

So I checked my users table in the db and I _do_ have a username and it _does_ pass the regex validation. But when I go re-login it falls back into this redirect loop.

**Comment by mcrutch** [comment]
Sorry, I have been off working Jupyter extensions and such for a bit.  Not sure why it is doing that, I think we are just pressing forward with zeitwek errors for the moment until I can loop back and work on that, but I will check our logs just to be sure that is what we are doing right now

**Comment by cccs-cat001** [comment]
OH YEAH! Let me update you, I solved all our problems :D 

Part 1 was that change in application.rb, that fixed the zeitwerk issue, but then it brought back the redirect to user edit error. 

Part 2 being the user redirect edit thing. Something must've changed in ruby where the db queries are now case sensitive. Previously in my custom oidc authentication we were doing
```ruby
user = User.where(:email => email).first_or_create do |user|
# set up user
end
```
but once I added a `.downcase` we stopped getting the redirect loop:
```ruby
user = User.where(:email => email.downcase).first_or_create do |user|
# set up user
end
```
so it must've been not finding the user when matching the email case sensitive, so it would go to create a user. But because there is _already_ a user with that email but not matching the case it goes to edit. 

I don't consider myself a ruby developer but maybe I should start 🤔😂😂
