### ISSUE TITLE
Consolidated display name

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/nbgallery#9]
Per @kylekyle, we don't want to show people's email addresses so we need a different display name on the site. It could be their first name (since it doesn't have to be unique) or we could establish unique user names. Either way, we need to prompt users for a display name or unique username.

Per @somedave, @rfestag has thought about this a bit already - and if so hopefully he'll chime in here with his thoughts.

**Comment by fenwanderer** [comment]
@jeffyjefflabs - did you already take care of this by other means?

**Comment by somedave** [comment]
Yep @fenwanderer this is all addressed now.

**Comment by somedave** [comment]
Ha just reread where @jeffyjefflabs said this is almost done ;-)
