### ISSUE TITLE
Remove nbclassic from Environments launch option 

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#906]
Jupyter Classic has been deprecated by the opensource community so to prevent 404 errors need of people launching it, we should remove it as an option.

**Comment by mcrutch** [comment]
NBClassic is still supported for bug fixes until Notebook 8 comes about.  that option in the environments only works when Jupyter v7/Lab v4/NBClassic are installed but it is still very much a valid option.
