### ISSUE TITLE
 [Ruby 2.7 EOL] Query about NBGallery's Ruby Version Upgrade Plans

### ISSUE THREAD

**Issue by neojunjie** [nbgallery/nbgallery#956]
We have been grateful with NBGallery and its valuable role within our organization. With Ruby 2.7 reached end of life in March 2023 (https://endoflife.date/ruby), I wanted to inquire about your intentions to upgrade NBGallery to Ruby 3.X. 

Upgrading to the latest Ruby version is not only crucial for security and performance but also for staying in line with the evolving Ruby ecosystem. Can you please provide some insights into your plans for any upgrade and any associated timelines? 

Your response would greatly help us in understanding the direction NBGallery is headed in

**Comment by mcrutch** [comment]
To be honest, we just hadn't looked into it yet.  I started a branch and have a container running on Rails 3.0 in our dev environment and SO FAR nothing seems off, but we are still doing testing.  If 3.0 works, then we might try 3.1 in the near term but I can't make any solid promises.

**Comment by mcrutch** [comment]
Pre-release of the 3.1 image is here - nbgallery/nbgallery:ruby3.1-pre
So far testing is promising

**Comment by mcrutch** [comment]
nbgallery/nbgallery:2.0.0 is Ruby 3.1 based.  3.2+ may be looked at in the near future but that takes us till march 2025 at least.
